// import '../globals.css'
import './data.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Space Apps 2023',
  description: 'Generated by create next app',
}

function Footerbar() {
  return (
    <div id="backtomain"><a href="..">
      <h4>&#8592; Back to main page</h4>
    </a></div>
  )
}



export default function DataLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div id="demoimg"><div id="theimage">
      {children}
      <Footerbar />
    </div></div>
  );
}